# Generated by Django 5.2.1 on 2025-05-22 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=170, verbose_name='Address')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('rooms_count', models.PositiveSmallIntegerField(verbose_name='Rooms count')),
                ('room_type', models.CharField(choices=[('SINGLE_ROOM', 'Single room (studio)'), ('ONE_BEDROOM', 'One room with separate bedroom'), ('TWO_BEDROOM', 'Two rooms with shared bathroom'), ('TWO_BEDROOM_ENSUITE', 'Two rooms with private bathrooms'), ('THREE_BEDROOM', 'Three rooms'), ('SUITE', 'Suite / Apartment'), ('SHARED_ROOM', 'Shared room / Bed space'), ('PRIVATE_ROOM_IN_SHARED', 'Private room in shared apartment'), ('LOFT', 'Loft / Attic'), ('STUDIO', 'Studio')], max_length=45, verbose_name='Room type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'rent',
                'ordering': ['-created_at'],
            },
        ),
    ]
