# Generated by Django 5.2.1 on 2025-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
