# Generated by Django 5.2.1 on 2025-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rent_latitude_rent_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='city',
            field=models.CharField(default='Berlin', max_length=50),
            preserve_default=False,
        ),
    ]
