# Generated by Django 5.2.1 on 2025-05-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
    ]
